/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Ubuntu */
#define Linux 

/* Name of package */
#define PACKAGE "reliable_udp"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Lei Chen, Chao Sun, Azadeh Nematzadeh lc6@indiana.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "reliable_udp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "reliable_udp 0.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "reliable_udp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.0.1"

/* Version number of package */
#define VERSION "0.0.1"
